schema_version: 1

context:
  name: oras
  version: "1.3.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/oras-project/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 33a44023666e00b6e32b5bd022a77f0813a488bdeab90c7d728b811d5f97df48

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p $PREFIX/bin

    - if: osx
      then:
        - make build-mac-${{ "arm64" if target_platform == "osx-arm64" else "amd64" }}
        - mv bin/darwin/${{ "arm64" if target_platform == "osx-arm64" else "amd64" }}/oras $PREFIX/bin/oras

    - if: linux
      then:
        - make build-linux-${{ "arm64" if target_platform == "linux-aarch64" else "amd64" }}
        - mv bin/linux/${{ "arm64" if target_platform == "linux-aarch64" else "amd64" }}/oras $PREFIX/bin/oras

    - if: unix
      then:
        # Make sure a binary has been installed for all unix platforms
        - which oras
        - bash $RECIPE_DIR/collect_licenses.sh

    - if: win
      then:
        - setlocal enableextensions
        - mkdir -p %PREFIX%\Library\bin
        - make build-windows-amd64
        - move bin\windows\amd64\oras.exe %PREFIX%\Library\bin\oras.exe
        - bash %RECIPE_DIR%\collect_licenses.sh

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - {if: win, then: m2-make, else: make}
    - go-licenses

tests:
  - script:
    - oras --help

about:
  homepage: https://github.com/oras-project/oras
  documentation: https://oras.land/
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: ORAS project provides a way to push and pull OCI Artifacts to and from OCI Registries.

extra:
  recipe-maintainers:
    - borchero
    - wolfv
    - janjagusch
